name: padellers-api

databases:
- name: padellers-db
  engine: PG
  version: "15"
  size: db-s-dev-database

services:
- name: api
  source_dir: /
  github:
    repo: alvaroprtm/padellers-ecommerce-backend
    branch: main
  
<<<<<<< HEAD
  build_command: chmod +x build.sh && ./build.sh
  run_command: php artisan serve --host=0.0.0.0 --port=8080
  
  environment_slug: php
=======
  dockerfile_path: Dockerfile
  
>>>>>>> 74bf878 (Fix SQLite setup for DigitalOcean App Platform)
  instance_count: 1
  instance_size_slug: basic-xxs
  
  envs:
  - key: APP_NAME
    value: "Padellers API"
  - key: APP_ENV
    value: production
  - key: APP_DEBUG
    value: "false"
  - key: DB_CONNECTION
    value: pgsql
  - key: DB_HOST
    value: ${padellers-db.HOSTNAME}
  - key: DB_PORT
    value: ${padellers-db.PORT}
  - key: DB_DATABASE
<<<<<<< HEAD
    value: ${padellers-db.DATABASE}
  - key: DB_USERNAME
    value: ${padellers-db.USERNAME}
  - key: DB_PASSWORD
    value: ${padellers-db.PASSWORD}
=======
    value: /app/database/database.sqlite
  - key: DB_FOREIGN_KEYS
    value: "true"
>>>>>>> 74bf878 (Fix SQLite setup for DigitalOcean App Platform)
  - key: CACHE_DRIVER
    value: file
  - key: SESSION_DRIVER
    value: file
  - key: QUEUE_CONNECTION
    value: database
    
  routes:
  - path: /