name: padellers-api
services:
- name: api
  source_dir: /
  github:
    repo: alvaroprtm/padellers-ecommerce-backend
    branch: main
  
  dockerfile_path: Dockerfile
  
  instance_count: 1
  instance_size_slug: basic-xxs
  
  envs:
  - key: APP_NAME
    value: "Padellers API"
  - key: APP_ENV
    value: production
  - key: APP_DEBUG
    value: "true"
  - key: DB_CONNECTION
    value: sqlite
  - key: DB_DATABASE
    value: /workspace/database/database.sqlite
  - key: DB_FOREIGN_KEYS
    value: "true"
  - key: CACHE_DRIVER
    value: file
  - key: SESSION_DRIVER
    value: file
  - key: QUEUE_CONNECTION
    value: database
  - key: LOG_LEVEL
    value: debug
  - key: MAIL_MAILER
    value: log
  - key: MAIL_FROM_ADDRESS
    value: "noreply@padellers.com"
  - key: MAIL_FROM_NAME
    value: "Padellers"
    
  routes:
  - path: /